spring:
  datasource:
    url: jdbc:h2:mem:w2m
    username: w2m
    password: w2m
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

# secret = w2m
jwt:
  secret: dzJt
  validity: 1800
